MA_HRS/MA_HRS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

MA_HRS/home/urls.py
from django.urls import path, include
from home import views


app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        # path('login', views.user_login, name='user-login'),
        # path('logout/', views.user_logout, name='logout'),
        # path('add-user/', views.addUserView, name='new-user'),
        # path('register/', views.register, name='register'),
        path('', views.homepage, name='homepage'),
]

MA_HRS/MA_HRS/templates/footer.html
{% load static %}

<footer class="footerCustom">
  <div class="credits">
    Designed by <a target="_blank" href="http://www.mashreqarabia.com">Mashreq Arabia for Techno Investments 2020</a>
  </div>
</footer>

MA_HRS/MA_HRS/templates/main_temp.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>Creative - Bootstrap Admin Template</title>

  <!-- Bootstrap CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="css/bootstrap-theme.css" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="css/elegant-icons-style.css" rel="stylesheet" />
  <link href="css/font-awesome.min.css" rel="stylesheet" />
  <!-- full calendar css-->
  <link href="assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
  <link href="assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
  <!-- easy pie chart-->
  <link href="assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
  <!-- owl carousel -->
  <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
  <link href="css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
  <!-- Custom styles -->
  <link rel="stylesheet" href="css/fullcalendar.css">
  <link href="css/widgets.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
  <link href="css/style-responsive.css" rel="stylesheet" />
  <link href="css/xcharts.min.css" rel=" stylesheet">
  <link href="css/jquery-ui-1.10.4.min.css" rel="stylesheet">
</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <header class="header dark-bg">
      {% include 'top_nav.html' %}
    </header>
    <!--sidebar start-->
    <aside>
      {% include 'side_nav.html' %}
    </aside>
    <!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
    {% block body %}
    {% endblock body %}
    </section>
    {% include 'footer.html' %}

    <!--main content end-->
  </section>

  <!-- container section start -->

  <!-- javascripts -->
  <script src="js/jquery.js"></script>
  <script src="js/jquery-ui-1.10.4.min.js"></script>
  <script src="js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript" src="js/jquery-ui-1.9.2.custom.min.js"></script>
  <!-- bootstrap -->
  <script src="js/bootstrap.min.js"></script>
  <!-- nice scroll -->
  <script src="js/jquery.scrollTo.min.js"></script>
  <script src="js/jquery.nicescroll.js" type="text/javascript"></script>
  <!-- charts scripts -->
  <script src="assets/jquery-knob/js/jquery.knob.js"></script>
  <script src="js/jquery.sparkline.js" type="text/javascript"></script>
  <script src="assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
  <script src="js/owl.carousel.js"></script>
  <!-- jQuery full calendar -->
  <<script src="js/fullcalendar.min.js">
    </script>
    <!-- Full Google Calendar - Calendar -->
    <script src="assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <!--script for this page only-->
    <script src="js/calendar-custom.js"></script>
    <script src="js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="js/jquery.customSelect.min.js"></script>
    <script src="assets/chart-master/Chart.js"></script>

    <!--custome script for all page-->
    <script src="js/scripts.js"></script>
    <!-- custom script for this page-->
    <script src="js/sparkline-chart.js"></script>
    <script src="js/easy-pie-chart.js"></script>
    <script src="js/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="js/jquery-jvectormap-world-mill-en.js"></script>
    <script src="js/xcharts.min.js"></script>
    <script src="js/jquery.autosize.min.js"></script>
    <script src="js/jquery.placeholder.min.js"></script>
    <script src="js/gdp-data.js"></script>
    <script src="js/morris.min.js"></script>
    <script src="js/sparklines.js"></script>
    <script src="js/charts.js"></script>
    <script src="js/jquery.slimscroll.min.js"></script>
    <script>
      //knob
      $(function() {
        $(".knob").knob({
          'draw': function() {
            $(this.i).val(this.cv + '%')
          }
        })
      });

      //carousel
      $(document).ready(function() {
        $("#owl-slider").owlCarousel({
          navigation: true,
          slideSpeed: 300,
          paginationSpeed: 400,
          singleItem: true

        });
      });

      //custom select box

      $(function() {
        $('select.styled').customSelect();
      });

      /* ---------- Map ---------- */
      $(function() {
        $('#map').vectorMap({
          map: 'world_mill_en',
          series: {
            regions: [{
              values: gdpData,
              scale: ['#000', '#000'],
              normalizeFunction: 'polynomial'
            }]
          },
          backgroundColor: '#eef3f7',
          onLabelShow: function(e, el, code) {
            el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
          }
        });
      });
    </script>
</body>

</html>

MA_HRS/MA_HRS/templates/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

  <title>Mashreq HR</title>

  <!-- Bootstrap CSS -->
  <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- full calendar css-->
  <link href="{% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
  <!-- easy pie chart-->
  <link href="{% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
  <!-- owl carousel -->
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
  <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
  <!-- Custom styles -->
  <link rel="{% static 'stylesheet' %}" href="css/fullcalendar.css">
  <link href="{% static 'css/widgets.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
  <link href="{% static 'css/xcharts.min.css' %}" rel=" stylesheet">
  <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <header class="header dark-bg">
      {% include 'top_nav.html' %}
    </header>
    <!--sidebar start-->
    <aside>
      {% include 'side_nav.html' %}
    </aside>
    <!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
      {% block body %}
      {% endblock body %}
    </section>
    {% include 'footer.html' %}

    <!--main content end-->
  </section>


  <!-- javascripts -->
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
  <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}"></script>
  <!-- bootstrap -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!-- charts scripts -->
  <script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
  <script src="{% static 'js/jquery.sparkline.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js' %}"></script>
  <script src="{% static 'js/owl.carousel.js' %}"></script>
  <!-- jQuery full calendar -->
  <<script src="{% static 'js/fullcalendar.min.js' %}">
    </script>
    <!-- Full Google Calendar - Calendar -->
    <script src="{% static 'assets/fullcalendar/fullcalendar/fullcalendar.js' %}"></script>
    <!--script for this page only-->
    <script src="{% static 'js/calendar-custom.js' %}"></script>
    <script src="{% static 'js/jquery.rateit.min.js' %}"></script>
    <!-- custom select -->
    <script src="{% static 'js/jquery.customSelect.min.js' %}"></script>
    <script src="{% static 'assets/chart-master/Chart.js' %}"></script>

    <!--custome script for all page-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- custom script for this page-->
    <script src="{% static 'js/sparkline-chart.js' %}"></script>
    <script src="{% static 'js/easy-pie-chart.js' %}"></script>
    <script src="{% static 'js/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'js/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'js/xcharts.min.js' %}"></script>
    <script src="{% static 'js/jquery.autosize.min.js' %}"></script>
    <script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
    <script src="{% static 'js/gdp-data.js' %}"></script>
    <script src="{% static 'js/morris.min.js' %}"></script>
    <script src="{% static 'js/sparklines.js' %}"></script>
    <script src="{% static 'js/charts.js' %}"></script>
    <script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
    <script>
      //knob
      $(function() {
        $(".knob").knob({
          'draw': function() {
            $(this.i).val(this.cv + '%')
          }
        })
      });

      //carousel
      $(document).ready(function() {
        $("#owl-slider").owlCarousel({
          navigation: true,
          slideSpeed: 300,
          paginationSpeed: 400,
          singleItem: true

        });
      });

      //custom select box

      $(function() {
        $('select.styled').customSelect();
      });

      /* ---------- Map ---------- */
      $(function() {
        $('#map').vectorMap({
          map: 'world_mill_en',
          series: {
            regions: [{
              values: gdpData,
              scale: ['#000', '#000'],
              normalizeFunction: 'polynomial'
            }]
          },
          backgroundColor: '#eef3f7',
          onLabelShow: function(e, el, code) {
            el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
          }
        });
      });
    </script>
</body>

</html>

MA_HRS/MA_HRS/templates/side_nav.html
{% load i18n %}
{% load l10n %}
{% load static %}


<div id="sidebar" class="nav-collapse ">
  <!-- sidebar menu start-->
  <ul class="sidebar-menu">
    <li class="sub-menu">
      <a href="javascript:;" class="">
        <i class="icon_document_alt"></i>
        <span>Employee Management</span>
        <span class="menu-arrow arrow_carrot-right"></span>
      </a>
      <ul class="sub">
        <li><a class="" href="form_component.html">Create Employee</a></li>
        <li><a class="" href="form_validation.html">List Employee</a></li>
      </ul>
    </li>
    <li class="sub-menu">
      <a href="javascript:;" class="">
        <i class="icon_desktop"></i>
        <span>Leave Management</span>
        <span class="menu-arrow arrow_carrot-right"></span>
      </a>
      <ul class="sub">
        <li><a class="" href="form_component.html">Leave Setup</a></li>
        <li><a class="" href="form_validation.html">Create Leave</a></li>
        <li><a class="" href="form_validation.html">List Leaves</a></li>
      </ul>
    </li>
    <li class="sub-menu">
      <a href="javascript:;" class="">
        <i class="icon_document_alt"></i>
        <span>Services Management</span>
        <span class="menu-arrow arrow_carrot-right"></span>
      </a>
      <ul class="sub">
        <li><a class="" href="form_component.html">Create Services</a></li>
        <li><a class="" href="form_validation.html">List Services</a></li>
      </ul>
    </li>
    <li>
      <a class="" href="chart-chartjs.html">
         <i class="icon_piechart"></i>
        <span>Recruitment System</span>
      </a>
    </li>
    <li>
      <a class="" href="chart-chartjs.html">
        <i class="icon_piechart"></i>
        <span>Attendence</span>
      </a>
    </li>
  </ul>
  <!-- sidebar menu end-->
</div>

MA_HRS/MA_HRS/templates/top_nav.html
{% load i18n %}
{% load l10n %}
{% load static %}

<!--logo start-->
<a href="{% url 'home:homepage'%}" class="logo">Mashreq <span class="lite">HRMS</span></a>
<!--logo end-->
<div class="nav search-row" id="top_menu">
  <!--  search form start -->
  <ul class="nav top-menu">
    <li>
      <a href="{% url 'home:homepage'%}"><i class="icon_house_alt"></i>Home</a>
    </li>
  </ul>
  <!--  search form end -->
</div>
<div class="top-nav notification-row">
  <!-- notificatoin dropdown start-->
  <ul class="nav pull-right top-menu">
    <!-- user login dropdown start-->
    <li class="dropdown">
      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <span><i class="fa fa-user"></i></span>
        <span class="username">Welcome {{request.user}}</span>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu extended logout">
        <div class="log-arrow-up"></div>
        <li>
          <a href="login.html"><i class="icon_key_alt"></i> Log Out</a>
        </li>
      </ul>
    </li>
    <!-- user login dropdown end -->
  </ul>
  <!-- notificatoin dropdown end-->
</div>
<!--header end-->